### ISSUE TITLE
Register ERR

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [GenesysGame/lw-rage#4]
Hey, again. 👍  
When I wanna register user got error, but user create in database (works). 
Here is screenshots:
(API server.js)
![api-server-cipher-err](https://user-images.githubusercontent.com/13278733/37283648-f8c19958-25f8-11e8-8426-8b74276ebce2.jpg)

(SERVER server.exe)
![server-post-error](https://user-images.githubusercontent.com/13278733/37283666-0779e1c6-25f9-11e8-8c16-a6c60076078c.jpg)

(GAME gtav.exe)
![server-post-error-game](https://user-images.githubusercontent.com/13278733/37283916-fab516c6-25f9-11e8-82ec-9c945a7c5441.jpg)

Thank you!

**Comment by BozhkoAlexander** [comment]
If you want to help us in development, please contact me by email ggame.studio@yandex.ru.
